#!/usr/bin/env python3
"""Generate frontend-owned shell completions from one reviewed CLI schema."""

from __future__ import annotations

import argparse
import difflib
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SPEC = ROOT / "dist" / "shell-completions" / "spec.json"
DEFAULT_OUTPUT_DIRECTORY = DEFAULT_SPEC.parent
GENERATED_NOTICE = "Generated by scripts/generate-shell-completions.py; do not edit."


def load_spec(path: Path) -> dict[str, Any]:
    spec = json.loads(path.read_text(encoding="utf-8"))
    if spec.get("command") != "ghostty-qt":
        raise ValueError("completion command must be ghostty-qt")

    option_names = [
        name for option in spec["options"] for name in option.get("names", [])
    ]
    if len(option_names) != len(set(option_names)):
        raise ValueError("top-level completion option names must be unique")

    action_names = [action["name"] for action in spec["actions"]]
    if len(action_names) != len(set(action_names)):
        raise ValueError("completion action names must be unique")
    if any(not name.startswith("+") for name in action_names):
        raise ValueError("completion action names must begin with +")
    application_ipc_actions = spec.get("application_ipc_actions", [])
    if not application_ipc_actions or not set(application_ipc_actions).issubset(
        action_names
    ):
        raise ValueError("application IPC actions must name known completion actions")
    return spec


def shell_words(values: list[str]) -> str:
    return " ".join(values)


def option_candidates(options: list[dict[str, Any]]) -> list[str]:
    candidates: list[str] = []
    for option in options:
        names = option["names"] if "names" in option else [option["name"]]
        for name in names:
            if option["kind"] == "value" and name.startswith("--"):
                candidates.append(f"{name}=")
            else:
                candidates.append(name)
    return candidates


def bash_case_pattern(action: str, option: str) -> str:
    return f"{action}:{option}" if action else f":{option}"


def bash_value_body(option: dict[str, Any], prefix: str = "    ") -> list[str]:
    choices = option.get("choices", [])
    completion = option.get("completion")
    if completion == "font":
        return [
            f"{prefix}while IFS= read -r candidate; do",
            f'{prefix}  [[ $candidate == "$value"* ]] || continue',
            f'{prefix}  COMPREPLY+=("$reply_prefix$candidate " )',
            f"{prefix}done < <(command ghostty-qt +list-fonts 2>/dev/null | grep '^[A-Z]')",
        ]
    if completion == "directory":
        quoted_choices = shell_words(choices)
        lines = [
            f"{prefix}while IFS= read -r candidate; do",
            f'{prefix}  COMPREPLY+=("$reply_prefix$candidate " )',
            f"{prefix}done < <(compgen -W '{quoted_choices}' -- \"$value\")",
            f"{prefix}while IFS= read -r candidate; do",
            f'{prefix}  COMPREPLY+=("$reply_prefix$candidate/")',
            f'{prefix}done < <(compgen -d -- "$value")',
        ]
        return lines
    if completion == "file":
        return [
            f"{prefix}compopt -o filenames 2>/dev/null || true",
            f"{prefix}while IFS= read -r candidate; do",
            f'{prefix}  COMPREPLY+=("$reply_prefix$candidate")',
            f'{prefix}done < <(compgen -f -- "$value")',
        ]
    if completion == "command":
        return [
            f"{prefix}while IFS= read -r candidate; do",
            f'{prefix}  COMPREPLY+=("$reply_prefix$candidate " )',
            f'{prefix}done < <(compgen -c -- "$value")',
        ]
    if choices:
        return [
            f"{prefix}while IFS= read -r candidate; do",
            f'{prefix}  COMPREPLY+=("$reply_prefix$candidate " )',
            f"{prefix}done < <(compgen -W '{shell_words(choices)}' -- \"$value\")",
        ]
    return [f"{prefix}return 0"]


def render_bash(spec: dict[str, Any]) -> str:
    actions = spec["actions"]
    top_candidates = (
        option_candidates(spec["options"])
        + ["--"]
        + [action["name"] for action in actions]
    )

    lines = [
        f"# {GENERATED_NOTICE}",
        "",
        "_ghostty_qt_reply_words()",
        "{",
        "  local words=$1 value=$2 candidate",
        "  while IFS= read -r candidate; do",
        '    [[ $candidate == *= ]] && COMPREPLY+=("$candidate") || COMPREPLY+=("$candidate " )',
        '  done < <(compgen -W "$words" -- "$value")',
        "}",
        "",
        "_ghostty_qt_complete_value()",
        "{",
        "  local action=$1 option=$2 value=$3 reply_prefix=$4 candidate",
        '  case "$action:$option" in',
    ]

    for option in spec["options"]:
        if option["kind"] not in {"value", "optional-value"}:
            continue
        for name in option["names"]:
            lines.append(f"  {bash_case_pattern('', name)})")
            lines.extend(bash_value_body(option))
            lines.append("    ;;")

    for action in actions:
        for option in action["options"]:
            if option["kind"] not in {"value", "optional-value"}:
                continue
            lines.append(f"  {bash_case_pattern(action['name'], option['name'])})")
            lines.extend(bash_value_body(option))
            lines.append("    ;;")

    lines.extend(
        [
            "  *) return 1 ;;",
            "  esac",
            "  return 0",
            "}",
            "",
            "_ghostty_qt()",
            "{",
            "  local cur prev action='' boundary=-1 option='' value='' reply_prefix=''",
            "  local i word candidate",
            "  COMPREPLY=()",
            "  cur=${COMP_WORDS[COMP_CWORD]}",
            "  prev=''",
            "  (( COMP_CWORD > 0 )) && prev=${COMP_WORDS[COMP_CWORD-1]}",
            "",
            "  for ((i = 1; i < COMP_CWORD; ++i)); do",
            "    word=${COMP_WORDS[i]}",
            "    if [[ $word == -e || $word == -- ]]; then",
            "      boundary=$i",
            "      break",
            "    fi",
            "    [[ $word == +* ]] && action=$word",
            "  done",
            "",
            "  if (( boundary >= 0 )); then",
            "    if (( COMP_CWORD == boundary + 1 )); then",
            '      while IFS= read -r candidate; do COMPREPLY+=("$candidate " ); done < <(compgen -c -- "$cur")',
            "    else",
            "      compopt -o filenames 2>/dev/null || true",
            '      mapfile -t COMPREPLY < <(compgen -f -- "$cur")',
            "    fi",
            "    return 0",
            "  fi",
            "",
            "  if [[ $cur == --*=* ]]; then",
            "    option=${cur%%=*}",
            "    value=${cur#*=}",
            "    reply_prefix=$option=",
            '    _ghostty_qt_complete_value "$action" "$option" "$value" "$reply_prefix"',
            "    return 0",
            "  fi",
            "  if [[ $cur == '=' ]]; then",
            "    option=$prev",
            "    _ghostty_qt_complete_value \"$action\" \"$option\" '' ''",
            "    return 0",
            "  fi",
            "  if [[ $prev == '=' && $COMP_CWORD -gt 1 ]]; then",
            "    option=${COMP_WORDS[COMP_CWORD-2]}",
            '    _ghostty_qt_complete_value "$action" "$option" "$cur" \'\'',
            "    return 0",
            "  fi",
            "",
            "  if [[ -z $action ]]; then",
            "    case $prev in",
        ]
    )
    top_value_names = [
        name
        for option in spec["options"]
        if option["kind"] == "value"
        for name in option["names"]
    ]
    lines.append(f"    {' | '.join(top_value_names)})")
    lines.extend(
        [
            "      _ghostty_qt_complete_value '' \"$prev\" \"$cur\" ''",
            "      return 0",
            "      ;;",
            "    esac",
            "  fi",
            "",
            "  if [[ -n $action ]]; then",
            "    case $action in",
        ]
    )
    for action in actions:
        candidates = option_candidates(action["options"]) + ["--help"]
        lines.extend(
            [
                f"    {action['name']})",
                f"      _ghostty_qt_reply_words '{shell_words(candidates)}' \"$cur\"",
                "      return 0",
                "      ;;",
            ]
        )
    lines.extend(
        [
            "    esac",
            "  fi",
            "",
            f"  _ghostty_qt_reply_words '{shell_words(top_candidates)}' \"$cur\"",
            "}",
            "",
            "complete -o nospace -o bashdefault -F _ghostty_qt ghostty-qt",
            "",
        ]
    )
    return "\n".join(lines)


def fish_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "\\'")


def fish_completion_expression(option: dict[str, Any]) -> str | None:
    choices = option.get("choices", [])
    completion = option.get("completion")
    if completion == "font":
        return "(ghostty-qt +list-fonts 2>/dev/null | string match -r '^[A-Z].*')"
    if completion == "directory":
        return f"{shell_words(choices)} (__fish_complete_directories)"
    if completion == "command" or option["kind"] == "command":
        return "(__fish_complete_command)"
    if choices:
        return shell_words(choices)
    return None


def fish_option_line(command: str, condition: str, option: dict[str, Any]) -> str:
    parts = ["complete", "-c", command, "-n", f"'{condition}'"]
    names = option["names"] if "names" in option else [option["name"]]
    for name in names:
        if name.startswith("--"):
            parts.extend(["-l", name[2:]])
        elif name.startswith("-") and len(name) == 2:
            parts.extend(["-s", name[1:]])

    if option["kind"] in {"value", "command"}:
        parts.append("-r")
    if option.get("completion") == "file":
        parts.append("-F")
    else:
        parts.append("-f")
    expression = fish_completion_expression(option)
    if expression:
        parts.extend(["-a", f"'{fish_escape(expression)}'"])
    parts.extend(["-d", f"'{fish_escape(option['description'])}'"])
    return " ".join(parts)


def render_fish(spec: dict[str, Any]) -> str:
    command = spec["command"]
    lines = [
        f"# {GENERATED_NOTICE}",
        "",
        "function __ghostty_qt_before_command",
        "    set -l words (commandline -opc)",
        "    set -e words[1]",
        "    for word in $words",
        "        switch $word",
        "            case -e -- '+*'",
        "                return 1",
        "        end",
        "    end",
        "    return 0",
        "end",
        "",
        "function __ghostty_qt_after_command_boundary",
        "    set -l words (commandline -opc)",
        "    set -e words[1]",
        "    for word in $words",
        "        switch $word",
        "            case -e --",
        "                return 0",
        "        end",
        "    end",
        "    return 1",
        "end",
        "",
        f"complete -c {command} -f",
        f"complete -c {command} -n '__ghostty_qt_after_command_boundary' -F",
    ]
    for option in spec["options"]:
        lines.append(fish_option_line(command, "__ghostty_qt_before_command", option))
    lines.append(
        f"complete -c {command} -n '__ghostty_qt_before_command' -f -a "
        "\"'--'\" -d 'Treat remaining arguments as the command'"
    )
    lines.append("")
    for action in spec["actions"]:
        lines.append(
            f"complete -c {command} -n '__ghostty_qt_before_command' -f "
            f"-a '{fish_escape(action['name'])}' "
            f"-d '{fish_escape(action['description'])}'"
        )
    lines.append("")
    for action in spec["actions"]:
        condition = f"__fish_seen_subcommand_from {action['name']}"
        lines.append(
            f"complete -c {command} -n '{condition}' -l help -f "
            "-d 'Show help for this action'"
        )
        for option in action["options"]:
            lines.append(fish_option_line(command, condition, option))
        lines.append("")
    return "\n".join(lines)


def zsh_double_quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\")
    escaped = escaped.replace('"', '\\"').replace("$", "\\$")
    return f'"{escaped}"'


def zsh_option_spec(option: dict[str, Any], name: str) -> str:
    description = option["description"]
    if option["kind"] in {"flag", "optional-value"}:
        return f"{name}[{description}]"

    value = option.get("value", "value")
    choices = option.get("choices", [])
    completion = option.get("completion")
    completer = ""
    if completion == "font":
        completer = "_ghostty_qt_fonts"
    elif completion == "directory":
        completer = "_ghostty_qt_directories"
    elif completion == "file":
        completer = "_files"
    elif completion == "command" or option["kind"] == "command":
        completer = "_command_names"
    elif choices:
        completer = f"({shell_words(choices)})"
    separator = "=" if name.startswith("--") else ""
    return f"{name}{separator}[{description}]:{value}:{completer}"


def render_zsh(spec: dict[str, Any]) -> str:
    command = spec["command"]
    lines = [
        f"#compdef {command}",
        f"# {GENERATED_NOTICE}",
        "",
        "_ghostty_qt_fonts() {",
        "  local -a fonts",
        "  fonts=(\"${(@f)$(ghostty-qt +list-fonts 2>/dev/null | grep '^[A-Z]')}\")",
        "  _describe -t fonts 'font family' fonts",
        "}",
        "",
        "_ghostty_qt_directories() {",
        "  _alternative 'special:special directory:(home inherit)' 'directories:directory:_directories'",
        "}",
        "",
        "_ghostty_qt() {",
        "  local context state state_descr line",
        "  typeset -A opt_args",
        "  local -a actions",
        "  actions=(",
    ]
    for action in spec["actions"]:
        lines.append(
            f"    {zsh_double_quote(action['name'] + ':' + action['description'])}"
        )
    lines.extend(["  )", "", "  _arguments -C \\"])
    top_specs: list[str] = []
    for option in spec["options"]:
        for name in option["names"]:
            top_specs.append(zsh_option_spec(option, name))
    top_specs.extend(["1:action:->actions", "*::argument:->arguments"])
    for index, option_spec in enumerate(top_specs):
        continuation = " \\" if index + 1 < len(top_specs) else ""
        lines.append(f"    {zsh_double_quote(option_spec)}{continuation}")
    lines.extend(
        [
            "",
            "  case $state in",
            "    (actions)",
            "      _describe -t actions 'Ghostty action' actions",
            "      ;;",
            "    (arguments)",
            "      case $words[2] in",
        ]
    )
    for action in spec["actions"]:
        action_specs = [
            zsh_option_spec(option, option["name"]) for option in action["options"]
        ]
        action_specs.append("--help[Show help for this action]")
        positional = action.get("positional")
        if positional == "ssh":
            action_specs.append("*:SSH argument:_ssh")
        elif positional == "command":
            action_specs.append("*::command argument:_normal")
        else:
            action_specs.append("*:argument:_default")
        lines.append(f"        ({action['name']})")
        lines.append("          _arguments \\")
        for index, option_spec in enumerate(action_specs):
            continuation = " \\" if index + 1 < len(action_specs) else ""
            lines.append(f"            {zsh_double_quote(option_spec)}{continuation}")
        lines.append("          ;;")
    lines.extend(
        [
            "        (*) _normal ;;",
            "      esac",
            "      ;;",
            "  esac",
            "}",
            "",
            '_ghostty_qt "$@"',
            "",
        ]
    )
    return "\n".join(lines)


def rendered_shells(spec: dict[str, Any]) -> dict[str, str]:
    return {
        "ghostty-qt": render_bash(spec),
        "ghostty-qt.fish": render_fish(spec),
        "_ghostty-qt": render_zsh(spec),
    }


def outputs(spec: dict[str, Any]) -> dict[str, str]:
    generated = rendered_shells(spec)
    application_ipc_actions = set(spec["application_ipc_actions"])
    config_disabled_spec = {
        **spec,
        "actions": [
            action
            for action in spec["actions"]
            if action["name"] in application_ipc_actions
        ],
    }
    generated.update(
        {
            f"config-disabled/{name}": content
            for name, content in rendered_shells(config_disabled_spec).items()
        }
    )
    return generated


def check_output(path: Path, expected: str) -> bool:
    actual = path.read_text(encoding="utf-8") if path.exists() else ""
    if actual == expected:
        return True
    diff = difflib.unified_diff(
        actual.splitlines(keepends=True),
        expected.splitlines(keepends=True),
        fromfile=str(path),
        tofile=f"{path} (generated)",
    )
    sys.stderr.writelines(diff)
    return False


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify generated files")
    parser.add_argument("--spec", type=Path, default=DEFAULT_SPEC)
    parser.add_argument(
        "--output-directory", type=Path, default=DEFAULT_OUTPUT_DIRECTORY
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    spec = load_spec(args.spec)
    generated = outputs(spec)
    if args.check:
        return (
            0
            if all(
                check_output(args.output_directory / name, content)
                for name, content in generated.items()
            )
            else 1
        )

    args.output_directory.mkdir(parents=True, exist_ok=True)
    for name, content in generated.items():
        path = args.output_directory / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
