if(NOT DEFINED OUTPUT OR OUTPUT STREQUAL "")
    message(FATAL_ERROR "Missing build-contract stamp output path")
endif()
if(NOT DEFINED CONTRACT)
    message(FATAL_ERROR "Missing build-contract stamp value")
endif()
string(LENGTH "${CONTRACT}" contract_length)
if(NOT CONTRACT MATCHES "^[0-9a-f]+$" OR NOT contract_length EQUAL 64)
    message(FATAL_ERROR "Invalid build-contract stamp value")
endif()

cmake_path(GET OUTPUT PARENT_PATH output_directory)
file(MAKE_DIRECTORY "${output_directory}")
set(temporary_output "${OUTPUT}.tmp")
file(WRITE "${temporary_output}" "${CONTRACT}\n")
file(RENAME "${temporary_output}" "${OUTPUT}"
    RESULT rename_result)
if(rename_result)
    message(FATAL_ERROR "Unable to publish build-contract stamp: ${rename_result}")
endif()
